In [ ]:
!pipenv install numpy

In [1]:
import numpy as np

## 1. Create

In [13]:
data = np.random.rand(2, 3, 4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [14]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])

In [20]:
type(arr)

numpy.ndarray

## 2. Read

In [22]:
# Attributes
shape = data.shape
size = data.size
type = data.dtype

In [25]:
type

dtype('float64')

In [38]:
# Slicing
arr = data[0]
slicer = data[0][0,2]
reverse = data[-1]
singleval = data[0][0][0]

In [39]:
singleval

np.float64(0.2846059105408356)

In [37]:
data[1]

array([[0.54161931, 0.425746  , 0.51634971, 0.83820181],
       [0.48733523, 0.10762218, 0.73163294, 0.91612908],
       [0.87207273, 0.85749679, 0.96101916, 0.980795  ]])

## 3. Update

In [50]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [51]:
list2

array([0.44557643, 0.3630829 , 0.56974542, 0.8897153 , 0.71641202,
       0.70296856, 0.82445864, 0.45369313, 0.12681571, 0.49132945])

In [53]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mul = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [76]:
# Statistical Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.pow(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [77]:
power

np.int64(128)

In [80]:
data[0][0,0] = 1.0

In [84]:
data.sort()

data

array([[[0.28903717, 0.46318289, 0.99230324, 1.        ],
        [0.33734988, 0.75196054, 0.96606986, 0.9890923 ],
        [0.08663634, 0.15319283, 0.46154113, 0.50791018]],

       [[0.425746  , 0.51634971, 0.54161931, 0.83820181],
        [0.10762218, 0.48733523, 0.73163294, 0.91612908],
        [0.85749679, 0.87207273, 0.96101916, 0.980795  ]]])

In [85]:
print(data.shape)

(2, 3, 4)


In [92]:
data = data.reshape(2,2,-1) # -1 says we don't care about last one
data

array([[[0.28903717, 0.46318289, 0.99230324, 1.        , 0.33734988,
         0.75196054],
        [0.96606986, 0.9890923 , 0.08663634, 0.15319283, 0.46154113,
         0.50791018]],

       [[0.425746  , 0.51634971, 0.54161931, 0.83820181, 0.10762218,
         0.48733523],
        [0.73163294, 0.91612908, 0.85749679, 0.87207273, 0.96101916,
         0.980795  ]]])

In [100]:
zeroes = np.zeros(8)
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [101]:
zeroes = np.insert(zeroes, 2,1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


## 4. Delete

In [108]:
data

array([[[0.28903717, 0.46318289, 0.99230324, 1.        , 0.33734988,
         0.75196054],
        [0.96606986, 0.9890923 , 0.08663634, 0.15319283, 0.46154113,
         0.50791018]],

       [[0.425746  , 0.51634971, 0.54161931, 0.83820181, 0.10762218,
         0.48733523],
        [0.73163294, 0.91612908, 0.85749679, 0.87207273, 0.96101916,
         0.980795  ]]])

In [109]:
np.delete(data, 0, axis=1) # delete row

array([[[0.96606986, 0.9890923 , 0.08663634, 0.15319283, 0.46154113,
         0.50791018]],

       [[0.73163294, 0.91612908, 0.85749679, 0.87207273, 0.96101916,
         0.980795  ]]])

In [110]:
np.save('new array', data)

In [112]:
# load saved NumPy array
test = np.load("new array.npy")

In [113]:
test

array([[[0.28903717, 0.46318289, 0.99230324, 1.        , 0.33734988,
         0.75196054],
        [0.96606986, 0.9890923 , 0.08663634, 0.15319283, 0.46154113,
         0.50791018]],

       [[0.425746  , 0.51634971, 0.54161931, 0.83820181, 0.10762218,
         0.48733523],
        [0.73163294, 0.91612908, 0.85749679, 0.87207273, 0.96101916,
         0.980795  ]]])